// Package schemas contains Go types generated from Avro schemas.
//
// The types are plain data containers you can serialize to JSON or use with
// Pub/Sub and CloudEvents. They are generated by the `avrogo` tool from the
// .avsc files in this directory.
package schemas
