// Package schemas contains Go types generated from Avro schemas.
//
// The types are plain data containers you can serialize to JSON or use with
// Pub/Sub and CloudEvents. They are generated by the `avrogo` tool from the
// .avsc files in this directory.
//
//go:generate go tool avrogen -pkg schemas -encoders -o story-drafted-v1_gen.go -tags json:original story-drafted-v1.avsc
//go:generate go tool avrogen -pkg schemas -encoders -o story-uploaded-v1_gen.go -tags json:original story-uploaded-v1.avsc
//go:generate go tool avrogen -pkg schemas -encoders -o scenario-v1_gen.go -tags json:original scenario-v1.avsc
package schemas
