// Code generated by avrogen. DO NOT EDIT.

package schemas

import (
	"github.com/heetch/avro/avrotypegen"
)

type StoryDraftedV1 struct {
	TaskID        string `json:"taskID"`
	ArtifactCount int    `json:"artifactCount"`
}

// AvroRecord implements the avro.AvroRecord interface.
func (StoryDraftedV1) AvroRecord() avrotypegen.RecordInfo {
	return avrotypegen.RecordInfo{
		Schema: `{"fields":[{"name":"taskID","type":"string"},{"name":"artifactCount","type":"int"}],"name":"StoryDraftedV1","type":"record"}`,
		Required: []bool{
			0: true,
			1: true,
		},
	}
}
