// Code generated by avrogen. DO NOT EDIT.

package schemas

import (
	"github.com/heetch/avro/avrotypegen"
)

type StoryUploadedV1 struct {
	TaskID string `json:"taskID"`
}

// AvroRecord implements the avro.AvroRecord interface.
func (StoryUploadedV1) AvroRecord() avrotypegen.RecordInfo {
	return avrotypegen.RecordInfo{
		Schema: `{"fields":[{"name":"taskID","type":"string"}],"name":"StoryUploadedV1","type":"record"}`,
		Required: []bool{
			0: true,
		},
	}
}
