// Code generated by avro/gen. DO NOT EDIT.
package schemas

import (
	"github.com/hamba/avro/v2"
)

// StoryUploadedV1 is a generated struct.
type StoryUploadedV1 struct {
	TaskID string `avro:"taskID" json:"taskID"`
}

var schemaStoryUploadedV1 = avro.MustParse(`{"name":"StoryUploadedV1","type":"record","fields":[{"name":"taskID","type":"string"}]}`)

// Schema returns the schema for StoryUploadedV1.
func (o *StoryUploadedV1) Schema() avro.Schema {
	return schemaStoryUploadedV1
}

// Unmarshal decodes b into the receiver.
func (o *StoryUploadedV1) Unmarshal(b []byte) error {
	return avro.Unmarshal(o.Schema(), b, o)
}

// Marshal encodes the receiver.
func (o *StoryUploadedV1) Marshal() ([]byte, error) {
	return avro.Marshal(o.Schema(), o)
}
