// Code generated by avro/gen. DO NOT EDIT.
package schemas

import (
	"github.com/hamba/avro/v2"
)

// StoryDraftedV1 is a generated struct.
type StoryDraftedV1 struct {
	TaskID        string `avro:"taskID" json:"taskId"`
	ArtifactCount int    `avro:"artifactCount" json:"artifactCount"`
}

var schemaStoryDraftedV1 = avro.MustParse(`{"name":"StoryDraftedV1","type":"record","fields":[{"name":"taskID","type":"string"},{"name":"artifactCount","type":"int"}]}`)

// Schema returns the schema for StoryDraftedV1.
func (o *StoryDraftedV1) Schema() avro.Schema {
	return schemaStoryDraftedV1
}

// Unmarshal decodes b into the receiver.
func (o *StoryDraftedV1) Unmarshal(b []byte) error {
	return avro.Unmarshal(o.Schema(), b, o)
}

// Marshal encodes the receiver.
func (o *StoryDraftedV1) Marshal() ([]byte, error) {
	return avro.Marshal(o.Schema(), o)
}
